[[session]]
name = "Home 🏡"
path = "~"
startup_command = "l"

[[session]]
name = "Code 💻"
path = "~/main"
startup_command = "l"

[[session]]
name = "home config"
path = "~/main/dotfiles/"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"
