import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[font]
size = 13

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[window]
decorations = "buttonless"
opacity = 0.9
startup_mode = "Maximized"
blur = true
padding.y = 5
padding.x = 5

[scrolling]
history = 0

[cursor]
style.shape = "Beam"
style.blinking = "On"

[shell]
program = "tmux"
args = ["new-session", "-A", "-s", "general"]
